services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoel-you/data/mariadb
      
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoel-you/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
